trigger:
  - none  # Definir el branch que dispara el pipeline, por ejemplo, main

pool:
  vmImage: 'ubuntu-latest'  # Seleccionar la imagen de la máquina virtual para ejecutar el pipeline

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $organizationName = "ingenierodevops2023"
      $projectName = "Proyecto1"
      $adoHeader = @{
        Authorization=("Basic {0}" -f [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f "", "$(adoToken)"))))
      }
      $adoTaskUri = "https://dev.azure.com/$organizationName/$projectName/_apis/wit/workitems/`$Task?api-version=5.1"

      # Leer el archivo CSV
      $csvPath = "$(Build.SourcesDirectory)\US\data.csv"
      $csvData = Import-Csv -Path $csvPath

      foreach ($row in $csvData) {
        $title = "$($row.task) - $($row.asset) - $($row.control) - ($($row.expdate))"
        
        # Data retrieved from Incident (these values can be passed as pipeline variables)
        $description = "Check the task"

        # Define ADO variables

        $comments = "Description : <br />"
        $comments += $description

        # Generate JSON body to make the REST API call
        $body = @(
          @{
            op = "add"
            path = "/fields/System.Title"
            value = "$title"
          }
          @{
            op = "add"
            path = "/fields/System.Description"
            value = "$comments"
          }
          @{
            op = "add"
            path = "/fields/Microsoft.VSTS.Common.Priority"
            value = "$($row.impact)"
          }
          @{
            op = "add"
            path = "/fields/System.Tags"
            value = "$($row.tag1);$($row.tag2)"
          }
          @{
            op = "add"
            path = "/fields/System.AreaPath"
            value = "$($row.area)"
          }
          @{
            op = "add"
            path = "/fields/System.IterationPath"
            value = "$($row.iteration)"
          }
          @{
            op = "add"
            path = "/relations/-"
            value = @{
              rel = "System.LinkTypes.Hierarchy-Reverse"
              url = "https://dev.azure.com/ingenierodevops2023/Proyecto1/_apis/wit/workItems/" + $($row.feature)}
          }
        ) | ConvertTo-Json -Compress

        # REST API call
        Invoke-RestMethod -Uri $adoTaskUri -ContentType "application/json-patch+json" -Body $body -Headers $adoHeader -Method POST
      }
